version: '3.1'

services:
  web:
    image: cowrvalera/docker-ubuntu-apache-php:22.04-php8.2-ioncube-1.0.0
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./src:/var/www/html
    ports:
      - "127.0.0.1:80:80"